// ─── Shared Design System ────────────────────────────────────
// Single source of truth for colors, typography, and translations.
// Used by every screen in the app.

export const GREEN = '#0B6623';
export const GREEN_DARK = '#4CAF50';

export const Theme = {
  light: {
    bg: '#FAFAFA', card: '#FFFFFF', text: '#111', sub: '#888',
    hint: '#B0B0B0', line: '#EEEEEE', fill: '#F2F2F2',
    accent: GREEN, accentSoft: '#F0F7F1', accentMid: '#D5E8D4',
    sel: '#111', selBg: '#F0F0F0',
    inv: '#FFF', green: GREEN, bar: 'dark' as const,
    amber: '#F59E0B', amberSoft: '#FFFBEB', amberBorder: '#FCD34D',
    red: '#EF4444', redSoft: '#FEF2F2',
  },
  dark: {
    bg: '#000', card: '#111', text: '#EEE', sub: '#888',
    hint: '#444', line: '#1A1A1A', fill: '#1A1A1A',
    accent: GREEN_DARK, accentSoft: '#162016', accentMid: '#1E331E',
    sel: '#EEE', selBg: '#222',
    inv: '#FFF', green: GREEN_DARK, bar: 'light' as const,
    amber: '#F59E0B', amberSoft: '#1A1500', amberBorder: '#78350F',
    red: '#EF4444', redSoft: '#1A0000',
  },
};

export type ThemeColors = typeof Theme.light;

// ─── i18n ────────────────────────────────────────────────────
export type Lang = 'EN' | 'ES' | 'TO';

export const AppStrings: Record<Lang, Record<string, string>> = {
  EN: {
    home: 'Home', map: 'Map', community: 'Community', profile: 'Profile',
    going_around: 'Is it going around?', right_now: 'Right now near you',
    prediction: 'Coming this week', alerts: 'Alerts', no_alerts: 'No active alerts',
    quick_actions: 'Quick actions', your_impact: 'Your impact',
    recent_near: 'Recent near you', see_all: 'See all →',
    reports: 'reports', streak: 'streak', anomaly_found: 'anomaly found',
    photo_report: 'Photo Report', voice_report: 'Voice Report', family_report: 'Family Report',
    coming_soon: 'Coming Soon', coming_soon_desc: 'This feature is coming soon!',
    notifications: 'Notifications', no_notifs: 'No notifications yet',
    alert_detail: 'Alert Detail', recommendations: 'Recommendations',
    historical: 'Historical comparison', context: 'Environmental context',
    ai_explanation: 'AI Explanation',
    filter_all: 'All', filter_people: 'People', filter_animals: 'Animals', filter_env: 'Environment',
    filter_24h: '24h', filter_7d: '7d', filter_30d: '30d',
    community_title: 'Community', community_disclaimer: 'Community observations only. Not medical advice.',
    post_placeholder: 'What are you noticing in your area?',
    posts_anonymous: 'Posts are anonymous', post_btn: 'Post',
    add_reply: 'Add a reply...', replies: 'Replies',
    profile_title: 'Profile', anon_reporter: 'Anonymous Reporter',
    recent_reports: 'Recent reports', settings: 'Settings',
    language: 'Language', location: 'Location', notif_settings: 'Notifications',
    appearance_setting: 'Appearance', about: 'About',
    how_works: 'How OneHealth Works', privacy: 'Privacy Policy',
    how_ai: 'How Our AI Works', send_feedback: 'Send Feedback',
    log_out: 'Log Out', sign_up: 'Sign Up', log_in: 'Log In',
    auth_card_title: 'Track reports across devices',
    auth_card_desc: 'Create a free account to sync your history.',
    auth_anon_note: 'You can always use OneHealth anonymously',
    reports_anon_note: 'Reports remain anonymous even with an account',
    create_account: 'Create Account', already_have: 'Already have an account?',
    dont_have: "Don't have an account?", forgot_pw: 'Forgot password?',
    name_optional: 'Full Name (optional)', email: 'Email', password: 'Password',
    based_on: 'Based on', this_week: 'this week', updated: 'Updated',
    min_ago: 'min ago', normal: 'Normal for this season',
    slightly_elevated: 'Slightly elevated', low_activity: 'Low activity',
    watch: 'Watch', no_signals: 'No signals',
    not_medical: 'Not medical advice. For emergencies call 911.',
    above_baseline: 'above baseline', z_score: 'z-score', accelerating: 'accelerating',
    stay_home: 'Stay home if symptomatic', wash_hands: 'Wash hands frequently',
    avoid_crowds: 'Avoid crowded indoor spaces', seek_care: 'Seek care if fever persists 48+ hours',
    report_change: 'Report again if symptoms change',
    submitted: 'Submitted',
  },
  ES: {
    home: 'Inicio', map: 'Mapa', community: 'Comunidad', profile: 'Perfil',
    going_around: '¿Está circulando?', right_now: 'Ahora cerca de ti',
    prediction: 'Esta semana', alerts: 'Alertas', no_alerts: 'Sin alertas activas',
    quick_actions: 'Acciones rápidas', your_impact: 'Tu impacto',
    recent_near: 'Recientes cerca', see_all: 'Ver todo →',
    reports: 'reportes', streak: 'racha', anomaly_found: 'anomalía',
    photo_report: 'Foto', voice_report: 'Voz', family_report: 'Familia',
    coming_soon: 'Próximamente', coming_soon_desc: '¡Esta función viene pronto!',
    notifications: 'Notificaciones', no_notifs: 'Sin notificaciones',
    alert_detail: 'Detalle de alerta', recommendations: 'Recomendaciones',
    historical: 'Comparación histórica', context: 'Contexto ambiental',
    ai_explanation: 'Explicación IA',
    filter_all: 'Todo', filter_people: 'Personas', filter_animals: 'Animales', filter_env: 'Entorno',
    filter_24h: '24h', filter_7d: '7d', filter_30d: '30d',
    community_title: 'Comunidad', community_disclaimer: 'Solo observaciones. No es consejo médico.',
    post_placeholder: '¿Qué notas en tu área?',
    posts_anonymous: 'Las publicaciones son anónimas', post_btn: 'Publicar',
    add_reply: 'Agregar respuesta...', replies: 'Respuestas',
    profile_title: 'Perfil', anon_reporter: 'Reportero Anónimo',
    recent_reports: 'Reportes recientes', settings: 'Configuración',
    language: 'Idioma', location: 'Ubicación', notif_settings: 'Notificaciones',
    appearance_setting: 'Apariencia', about: 'Acerca de',
    how_works: 'Cómo funciona', privacy: 'Privacidad',
    how_ai: 'Cómo funciona nuestra IA', send_feedback: 'Enviar comentarios',
    log_out: 'Cerrar sesión', sign_up: 'Registrarse', log_in: 'Iniciar sesión',
    auth_card_title: 'Sincroniza tus reportes',
    auth_card_desc: 'Crea una cuenta gratis para sincronizar.',
    auth_anon_note: 'Siempre puedes usar OneHealth anónimamente',
    reports_anon_note: 'Los reportes permanecen anónimos',
    create_account: 'Crear Cuenta', already_have: '¿Ya tienes cuenta?',
    dont_have: '¿No tienes cuenta?', forgot_pw: '¿Olvidaste tu contraseña?',
    name_optional: 'Nombre (opcional)', email: 'Correo', password: 'Contraseña',
    based_on: 'Basado en', this_week: 'esta semana', updated: 'Actualizado',
    min_ago: 'min', normal: 'Normal para la temporada',
    slightly_elevated: 'Ligeramente elevado', low_activity: 'Baja actividad',
    watch: 'Vigilar', no_signals: 'Sin señales',
    not_medical: 'No es consejo médico. Emergencias: 911.',
    above_baseline: 'sobre la línea base', z_score: 'z-score', accelerating: 'acelerando',
    stay_home: 'Quédate en casa si tienes síntomas', wash_hands: 'Lávate las manos',
    avoid_crowds: 'Evita espacios cerrados', seek_care: 'Busca atención si la fiebre persiste',
    report_change: 'Reporta si los síntomas cambian',
    submitted: 'Enviado',
  },
  TO: {
    home: 'Home', map: 'Map', community: 'Community', profile: 'Profile',
    going_around: 'S-ko:k ap?', right_now: 'I:da',
    prediction: 'I:da domig', alerts: 'Alerts', no_alerts: 'Pi haicu',
    quick_actions: 'Quick', your_impact: 'E-a:ga',
    recent_near: 'Haicu e-we:hejed', see_all: 'Ñei →',
    reports: 'reportes', streak: 'racha', anomaly_found: 'anomalía',
    photo_report: 'Koaia', voice_report: 'Ñiok', family_report: 'Ha-ñiok',
    coming_soon: 'Cem', coming_soon_desc: 'Cem!',
    notifications: 'Notifications', no_notifs: 'Pi haicu',
    alert_detail: 'Alert', recommendations: 'Recommendations',
    historical: 'Historical', context: 'Context',
    ai_explanation: 'AI',
    filter_all: 'All', filter_people: 'Hemaajkam', filter_animals: "Ha'icu", filter_env: 'Jewed',
    filter_24h: '24h', filter_7d: '7d', filter_30d: '30d',
    community_title: 'Community', community_disclaimer: 'Pi ma:cina.',
    post_placeholder: 'Sha:ču ñei?',
    posts_anonymous: 'Anonymous', post_btn: 'Post',
    add_reply: 'A:g...', replies: 'Replies',
    profile_title: 'Profile', anon_reporter: 'Anonymous',
    recent_reports: 'Haicu', settings: 'Settings',
    language: 'Ñiok', location: 'Hebai', notif_settings: 'Notifications',
    appearance_setting: 'Appearance', about: 'About',
    how_works: 'How', privacy: 'Privacy',
    how_ai: 'AI', send_feedback: 'Feedback',
    log_out: 'Log Out', sign_up: 'Sign Up', log_in: 'Log In',
    auth_card_title: 'Sync', auth_card_desc: 'Create account.',
    auth_anon_note: 'Anonymous ok', reports_anon_note: 'Anonymous',
    create_account: 'Create', already_have: 'Have account?',
    dont_have: 'No account?', forgot_pw: 'Forgot?',
    name_optional: 'Name', email: 'Email', password: 'Password',
    based_on: 'Based on', this_week: 'this week', updated: 'Updated',
    min_ago: 'min', normal: 'Normal', slightly_elevated: 'Elevated',
    low_activity: 'Low', watch: 'Watch', no_signals: 'None',
    not_medical: 'Not medical advice. 911.',
    above_baseline: 'above', z_score: 'z-score', accelerating: 'accelerating',
    stay_home: 'Stay home', wash_hands: 'Wash hands',
    avoid_crowds: 'Avoid crowds', seek_care: 'Seek care',
    report_change: 'Report changes',
    submitted: 'Submitted',
  },
};
